---
description: "This example notebook outlines how to read in PARQUET files from an Amazon S3 bucket into\
  \ a pandas dataframe using AWS Wrangler Python library and upload it to DataRobot's AI Catalog.\nThen,\
  \ using this dataset, we'll create a project, deploy the top performing model to a DataRobot prediction\
  \ server, and make batch predictions with a test dataset."
file_name: Amazon_S3_End_to_End.ipynb
languages:
  - python
authors:
  - Biju Krishnan
  - João Gomes
authors_email:
  - biju.krishnan@datarobot.com
  - joao@datarobot.com
smoke_test:
  run_smoke_test: false
maintainers:
  - João Gomes
maintainers_email:
  - joao@datarobot.com
tags: []
title: DataRobot AutoML end-to-end with Amazon Athena
