---
title: Load Neo4j 4.4.11 Database from .dump File
file_name: 01_create_neo4j_db.ipynb
description: |-
  This notebook demonstrates how to restore a Neo4j 4.4.11 database 
  from a `.dump` file using the `neo4j-admin load` command. 
  It includes stopping any running instance, loading the dump, 
  and restarting the Neo4j service for local development or data migration.
languages:
  - python
authors:
  - Joel A. Gónogra
maintainers:
  - João Gomes
maintainers_email:
  - joao@datarobot.com
smoke_test:
  run_smoke_test: false
  user_permissions: []
tags:
  - neo4j
  - graph-database
  - knowledge-graph
  - dump-restore
  - fraud-detection
