---
title: Data Annotator App
file_name: data_annotator_app.ipynb
description: |-
  This notebook shows how to call a Flask app to easily annotate image data for an ML model.
languages:
  - python
maintainers:
  - Mel Hanna
maintainers_email:
  - melanie.hanna@datarobot.com
smoke_test:
  run_smoke_test: false
  user_permissions: []
tags: []
