description: This notebook walks you through the steps to train and host a SageMaker
  model that can be monitored in the DataRobot platform.
file_name: AWS_SageMaker_DataRobot_MLOps.ipynb
languages:
- python
maintainers:
- Oleksandr Saienko
- Mao Shun (AWS)
maintainers_email:
- oleksandr.saienko@datarobot.com
smoke_test:
  run_smoke_test: false
tags: []
title: Integrate Amazon SageMaker with DataRobot MLOps
