---
description: This notebook shares three Python functions which can pull out various accuracy metrics,
  feature impact, and feature effects from multiple models and plot them in one chart.
file_name: Multi-Model Analysis.ipynb
languages:
  - python
maintainers:
  - Jake Snyder
maintainers_email:
  - jake.snyder@datarobot.com
smoke_test:
  run_smoke_test: false
tags: []
title: Multi-Model Analysis
