---
description: "In this notebook, we demo the usage of the Google Cloud Natural Language API for sentiment\
  \ analysis to enrich a customer churn dataset.\nThe sentiment scores from the Google API helps improve\
  \ the model performance in predicting the likelihood of churn for each customer, without requiring the\
  \ user to train their own sentiment models."
file_name: GCP_enrich_sentiment.ipynb
languages:
  - python
maintainers:
  - Shu Li
maintainers_email:
  - shu.li@datarobot.com
smoke_test:
  run_smoke_test: false
tags: []
title: GCP API based enrichment of modeling datasets
