---
title:
  - Observability Starter for Anthropic Claude model
  - Observability Starter for AWS Bedrock models
  - Observability starter for Azure OpenAI models
  - Enable observability for PaLM 2
  - Observability Starter for HuggingFace Models
  - Observability Starter for Langchain LLMChain based solutions
file_name:
  - anthropic_claude_observability_starter.ipynb
  - bedrock_titan_observability_starter.ipynb
  - gpt_observability_starter.ipynb
  - palm2_observability_starter.ipynb
  - huggingface_observability_starter.ipynb
  - llmchain_observability.ipynb
description: |-
  These accelerators shows how you can easily enable observability in your Anthropic AI, PaLM 2, Azure OpenAI, AWS Bedrock, Huggingface or LLMChain based Generative AI Solutions with DataRobot's LLMOps feature tools.
languages:
  - python
maintainers:
  - Abdul Jilani
maintainers_email:
  - abdul.jilani@datarobot.com
tags: []
smoke_test:
  run_smoke_test: false
