---
title: Feature engineering for molecular SMILES
file_name: Feature_Engineering_For_Molecular_SMILES.ipynb
description: |-
  SMILES (Simplified molecular input line entry system) is a textual representation of molecular structures. This guide introduces a feature engineering pipeline tailored for SMILES-formatted molecular data. It demonstrates how to convert raw SMILES strings into machine-learning-ready features using RDKit and other tools. It is recommended to run this notebook in a DataRobot codespace using a GPU environment.
languages:
  - python
maintainers:
  - Senkin Zhan
maintainers_email:
  - senkin.zhan@datarobot.com
smoke_test:
  run_smoke_test: false
tags: []
