---
description: This notebook outlines how to use zero-shot text classification with large language models
  (LLMs), focusing on its application in error analysis of supervised text classification models.
file_name: Zero Shot Test Classification for Error Analysis.ipynb
languages:
  - python
smoke_test:
  run_smoke_test: false
maintainers:
  - Glen Koundry
maintainers_email:
  - glen@datarobot.com
tags: []
title: Zero-shot text classification for error analysis
