---
description: This notebook outlines how to use zero-shot text classification with large language models
  (LLMs), focusing on its application in error analysis of supervised text classification models.
file_name: Zero Shot Test Classification for Error Analysis.ipynb
languages:
  - python
authors:
  - Glen Koundry
authors_email:
  - glen.koundry@datarobot.com
smoke_test:
  run_smoke_test: false
maintainers:
  - Chandler McCann
maintainers_email:
  - chandler.mccann@datarobot.com
tags: []
title: Zero-shot text classification for error analysis
