description: The notebook covers basic exploratory data analysis, running machine
  learning experiments in DataRobot and reviewing the results of those experiments
  to extract business insights and evaluate model accuracy.
file_name: Retail Industry - Predicting Factory Order Quantities for New Products.ipynb
languages:
- python
maintainers:
- Andrea Kropp
maintainers_email:
- andrea.kropp@datarobot.com
smoke_test:
  run_smoke_test: false
tags: []
title: Retail Industry - Predicting Factory Order Quantities for New Products
