title: Deploy Scoring Code as a microservice
file_name: Application.java
description: |-
  This AI Accelerator explains the step-by-step procedure to embed Scoring Code in a microservice and prepare it as the Docker container for a deployment on customer infrastructure (it can be self- or hyperscaler-managed K8s).
languages:
  - java
authors: 
  - Pavel Ustinov
authors_email:
  - pavel.ustinov@datarobot.com
tags: []