---
title: Synthetic data capability
file_name: dr_synth_data.ipynb
description: |-
  An example that uses python to create fake training data sets to model
languages:
  - python
maintainers:
  - David Abbott
maintainers_email:
  - david.abbott@datarobot.com
smoke_test:
  run_smoke_test: false
  user_permissions: []
tags: []
