description: "This notebook outlines how to recreate and customize DataRobot\u2019\
  s lift chart from a DataRobot blueprint (i.e., a modeling pipeline encompassing\
  \ the combination of data preprocessing steps and machine learning algorithm)."
file_name: customizing_lift_charts.ipynb
languages:
- python
maintainers:
- Taylor Larkin
maintainers_email:
- taylor.larkin@datarobot.com
smoke_test:
  run_smoke_test: false
tags: []
title: Customize lift charts
