description: This orchestration notebook illustrates the framework to integrate MLFlow
  and Papermill with the DataRobot API to run the experiment notebook with different
  parameters per experiment.
file_name: orchestration_notebook.ipynb
languages:
- python
maintainers:
- Chandler McCann
maintainers_email:
- chandler.mccann@datarobot.com
smoke_test:
  run_smoke_test: false
tags: []
title: Integrate MLFlow and Papermill to track ML experiments with DataRobot
