---
description: "This notebook illustrates an end-to-end demand forecasting workflow in DataRobot.\nTime\
  \ series forecasting in DataRobot has a suite of tools and approaches to handle highly complex multiseries\
  \ problems."
file_name: End_to_end_demand_forecasting_cold_start.ipynb
languages:
  - python
maintainers:
  - Andrii Kruchko
maintainers_email:
  - andrii.kruchko@datarobot.com
smoke_test:
  run_smoke_test: false
tags: []
title: 'End-to-end demand forecasting: cold start predictions'
