description: Take in the controller file from the first notebook, deploy the top models
  in each project, and add a "deployment" column to the controller.
file_name: Create_Deployments.ipynb
languages:
- python
maintainers:
- "Jo\xE3o Gomes"
maintainers_email:
- joao@datarobot.com
smoke_test:
  run_smoke_test: false
tags: []
title: Create a deployment
